config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :devices
  resources :managers
  resources :managers
  resources :sessions, only: [:new, :create, :destroy]
  root 'home#index'
  match '/contact', to: 'home#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :device_locations

  validates :name,  presence: true, length: { maximum: 100 }

end

app/models/device_location.rb
class DeviceLocation < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	belongs_to :device, dependent: :destroy

	validates :user_id, presence: true
	validates :device_id, presence: true
	validates :room, presence: true	


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :device_locations
	before_save { self.email = email.downcase}
	before_create :create_remember_token

	validates :name,  presence: true, length: { maximum: 50 }
  		VALID_EMAIL_REGEX = /\A[\w+\-.]+@perfectial+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		        uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

	def index
		@devices = Device.all.paginate(page: params[:page], per_page: 2)
	end

	def show
		@device = Device.find(params[:id])
 	end

	def new
		@device = Device.new
	end

	def create
		@device = Device.new(device_params)
		if @device.save       
      		redirect_to devices_path
		else
		  render 'devices/new'
		end
	end


	def edit
		@device = Device.find(params[:id])
  	end
  
	def update    
		@device = Device.find(params[:id])
	    if @device.update_attributes(device_params)
	      flash[:success] = "Device updated"
	      redirect_to devices_path
	    else
	      render 'edit'
	    end
  	end

	private 
	
	def device_params
		params.require(:device).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def contact

  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
	def index
		@devicesLocations = DeviceLocation.all
	end

	def new
		@devicesLocation = DeviceLocation.new
	end

	def create
		@devicesLocation = Device.new(device_params)
		if @devicesLocation.save       
      		redirect_to managers_path
		else
		  render 'devices/new'
		end
	end

	def update
		if @devicesLocation.update_attributes(user_params)
	      flash[:success] = "Profile updated"
	      redirect_to managers_path
    	else
      		render 'edit'
    	end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
      		redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      		render 'new'
		end
	end

	def destroy
		sign_out
    	redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action  :sigden_in_user , only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

 	def show
		@user = User.find(params[:id])
 	end

  def new
    @user = User.new
  end

	def create
		@user = User.new(user_params)
		if @user.save
       flash[:success] = "Welcome to the TDS!"
      redirect_to signin_path
		else
		  render 'new'
		end
	end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def edit
    
  end

  def update    
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

	private 
		def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def sigden_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      flash[:notice] = "You don't have permissions."
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/devices_locations_helper.rb
module DevicesLocationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def FullTitle(baseTitle, pageTitle)
		if pageTitle.empty?
			baseTitle
		else
			"#{baseTitle} | #{pageTitle}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user;
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user  = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end	

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user?(user)
    	user == current_user
  	end

  	#redirect
  	def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
   		session.delete(:return_to)
  	end

  	def store_location	
    	session[:return_to] = request.url if request.get?
  	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/devices/edit.html.erb
<% provide(:title, "Edit device") %>
<h2>Update device</h2>

<div class="row">
  <div class="span4 offset4">
    <%= form_for(@device) do |d| %>
      <%= d.label :name %>
      <%= d.text_field :name %>

      <%= d.label :description %>
      <%= d.text_field :description %>
      
      <%= d.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/devices/index.html.erb
<h1>Devices</h1>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= link_to 'Add New', new_device_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @devices.each do |d| %>
  <tr>
    <td><%= d.name %></td>
    <td><%= d.description %></td>
    <td><%= link_to 'Edit', edit_device_path(d) %></td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/devices/new.html.erb
<% provide(:title, 'Device') %>
<h1>Device</h1>

<div class="row">
  <div class="span4 offset4 ">
    <%= form_for(@device) do |d| %>
      <%= d.label :name %>
      <%= d.text_field :name %>

      <%= d.label :description %>
      <%= d.text_field :description %>

      <%= d.submit "Create device", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/devices/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @device.description %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/home/contact.html.erb
<div>
	contact page
</div>

app/views/home/index.html.erb
<% provide(:title, 'Home') %>

<div class="text-center">
	<h3>Welcome!</h3>
	<%=link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <h5>Perfectial</h5>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'http://perfectial.com/company' %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Tracking devices system", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
<!--                 <li><%= link_to "Settings", edit_user_path(current_user) %></li> -->
                <li><%= link_to "Devices", devices_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	   <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= FullTitle("TDS", yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>  
  
  <%= render 'layouts/shim' %>

</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
     <%= render 'layouts/header' %>
  </header>

    <div class="container">
      <%= yield %>

       <%= render 'layouts/footer' %>
    </div>
    
</body>
</html>

app/views/managers/index.html.erb
<h1>Manager</h1>
<table>
  <tr>
    <th>Device</th>
    <th>Room</th>
    <th>User</th>
  </tr>

<% @devicesLocations.each do |dl| %>
  <tr>
    <td><%= dl.device.name %></td>
    <td><%= dl.room %></td>
    <td><%= dl.user.email %></td>
  </tr>
<% end %>
</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h2>Update your profile</h2>

<div class="row">
  <div class="span4 offset4">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<%= will_paginate %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>

  <% @users.each do |u| %>
  <tr>
    <td><%= u.name %></td>
    <td><%= u.email %></td>
    <% if current_user.admin? || current_user?(u) %>
      <td><%= link_to 'Delete', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span4 offset4 ">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>